const tvFixture = ({ id, title, genreIds, keywords = [], country = "US", extra = {} }) => ({
  id,
  tmdbId: id,
  title,
  originalTitle: title,
  providerId: "tmdb",
  dataSource: "tmdb",
  source: "tmdb",
  mediaType: "tv",
  contentType: "drama",
  type: "drama",
  countryCodes: [country],
  countryValidation: "verified",
  genreIds,
  keywords,
  franchiseKey: `fixture:${id}`,
  ...extra,
});

export const GENRE_TAXONOMY_FIXTURES = Object.freeze({
  tvAction: tvFixture({ id: 940032, title: "Action Signal TV", genreIds: [10759], keywords: ["martial arts", "chase", "combat"] }),
  tvAdventure: tvFixture({ id: 940033, title: "Adventure Signal TV", genreIds: [10759], keywords: ["expedition", "treasure", "journey"] }),
  tvActionAdventure: tvFixture({ id: 940034, title: "Combined Action Adventure TV", genreIds: [10759] }),
  tvSf: tvFixture({ id: 940035, title: "Science Fiction Signal TV", genreIds: [10765], keywords: ["space", "robot", "future"], country: "JP" }),
  tvFantasy: tvFixture({ id: 940036, title: "Fantasy Signal TV", genreIds: [10765], keywords: ["magic", "dragon", "kingdom"], country: "JP" }),
  tvSfFantasy: tvFixture({ id: 940037, title: "Combined SF Fantasy TV", genreIds: [10765], country: "JP" }),
  tvWar: tvFixture({ id: 940038, title: "War Signal TV", genreIds: [10768], keywords: ["army", "soldier", "battle"], country: "GB" }),
  tvPolitics: tvFixture({ id: 940039, title: "Politics Signal TV", genreIds: [10768], keywords: ["election", "parliament", "government"], country: "GB" }),
  tvWarPolitics: tvFixture({ id: 940040, title: "Combined War Politics TV", genreIds: [10768], country: "GB" }),
  plainDrama: tvFixture({ id: 940041, title: "Plain Drama", genreIds: [18], keywords: ["family business"], country: "KR" }),
  romanceDrama: tvFixture({ id: 940141, title: "Romance Drama", genreIds: [18], keywords: ["first love", "romantic relationship"], country: "KR" }),
  plainMystery: tvFixture({ id: 940042, title: "Plain Mystery", genreIds: [9648], keywords: ["investigation"] }),
  horrorMystery: tvFixture({ id: 940142, title: "Horror Mystery", genreIds: [9648], keywords: ["ghost", "haunting"] }),
  tvMovie: tvFixture({ id: 940043, title: "TV Movie Format", genreIds: [10770] }),
  news: tvFixture({ id: 940143, title: "News Format", genreIds: [10763] }),
  reality: tvFixture({ id: 940243, title: "Reality Format", genreIds: [10764] }),
  talk: tvFixture({ id: 940343, title: "Talk Format", genreIds: [10767] }),
  soap: tvFixture({ id: 940443, title: "Soap Format", genreIds: [10766] }),
  family: tvFixture({ id: 940044, title: "Family Audience", genreIds: [10751] }),
  kids: tvFixture({ id: 940144, title: "Kids Audience", genreIds: [10762] }),
  animationOnly: tvFixture({ id: 940045, title: "Animation Style", genreIds: [16], extra: { contentType: "animation", type: "animation" } }),
  animationSf: tvFixture({ id: 940145, title: "Animation SF", genreIds: [16, 10765], keywords: ["space", "robot"], country: "JP", extra: { contentType: "animation", type: "animation" } }),
  animationFantasy: tvFixture({ id: 940245, title: "Animation Fantasy", genreIds: [16, 10765], keywords: ["magic", "dragon"], country: "JP", extra: { contentType: "animation", type: "animation" } }),
});

export function taxonomyFixturesForCase(caseId) {
  const fixtures = GENRE_TAXONOMY_FIXTURES;
  return {
    "REC-QA-032": [fixtures.tvAction],
    "REC-QA-033": [fixtures.tvAdventure],
    "REC-QA-034": [fixtures.tvActionAdventure],
    "REC-QA-035": [fixtures.tvSf],
    "REC-QA-036": [fixtures.tvFantasy],
    "REC-QA-037": [fixtures.tvSfFantasy],
    "REC-QA-038": [fixtures.tvWar],
    "REC-QA-039": [fixtures.tvPolitics],
    "REC-QA-040": [fixtures.tvWarPolitics],
    "REC-QA-041": [fixtures.plainDrama, fixtures.romanceDrama],
    "REC-QA-042": [fixtures.plainMystery, fixtures.horrorMystery],
    "REC-QA-043": [fixtures.tvMovie, fixtures.news, fixtures.reality, fixtures.talk, fixtures.soap],
    "REC-QA-044": [fixtures.family, fixtures.kids],
    "REC-QA-045": [fixtures.animationOnly, fixtures.animationSf, fixtures.animationFantasy],
    "REC-QA-046": [fixtures.tvAction, fixtures.tvAdventure, fixtures.tvSf, fixtures.tvFantasy, fixtures.tvWar, fixtures.tvPolitics],
  }[caseId] || [];
}
