const baseFixture = ({
  id,
  title,
  mediaType = "movie",
  contentType = mediaType === "tv" ? "drama" : "movie",
  genreIds = [18],
  keywords = [],
  country = "US",
  source = "tmdb-discover",
  popularity = 100,
  extra = {},
}) => ({
  id,
  tmdbId: id,
  title,
  originalTitle: title,
  providerId: "tmdb",
  dataSource: "tmdb",
  source: "tmdb",
  candidateSource: source,
  mediaType,
  providerMediaType: mediaType,
  contentType,
  type: contentType,
  displayContentType: contentType,
  countryCodes: [country],
  countryValidation: "verified",
  genreIds,
  providerGenreIds: genreIds,
  keywords,
  popularity,
  voteCount: 500,
  rating: 7.5,
  franchiseKey: `fixture:${id}`,
  ...extra,
});

const fixedMovieDescriptors = Object.freeze([
  [950101, "Seed Movie 01"], [950102, "Seed Movie 02"], [950103, "Seed Movie 03"],
  [950104, "Seed Movie 04"], [950105, "Seed Movie 05"], [950106, "Seed Movie 06"],
  [950107, "Seed Movie 07"], [950108, "Seed Movie 08"], [950109, "Seed Movie 09"],
  [950110, "Seed Movie 10"], [950111, "Seed Movie 11"], [950112, "Seed Movie 12"],
]);

const fixedTvDescriptors = Object.freeze([
  [950201, "Cross Media TV 01"], [950202, "Cross Media TV 02"],
  [950203, "Cross Media TV 03"], [950204, "Cross Media TV 04"],
  [950205, "Cross Media TV 05"], [950206, "Cross Media TV 06"],
  [950207, "Cross Media TV 07"], [950208, "Cross Media TV 08"],
]);

const fixedAnimationDescriptors = Object.freeze([
  [950301, "Cross Media Animation 01", "movie"],
  [950302, "Cross Media Animation 02", "movie"],
  [950303, "Cross Media Animation 03", "tv"],
  [950304, "Cross Media Animation 04", "tv"],
]);

const fixedAdventureDescriptors = Object.freeze([
  [950501, "Adventure Recall 01", ["journey", "expedition"], "popularity-page-1"],
  [950502, "Adventure Recall 02", ["quest", "treasure"], "popularity-page-1"],
  [950503, "Adventure Recall 03", ["exploration", "voyage"], "rating-page-1"],
  [950504, "Adventure Recall 04", ["wilderness", "journey"], "rating-page-1"],
  [950505, "Adventure Recall 05", ["travel", "expedition"], "popularity-page-2"],
  [950506, "Adventure Recall 06", ["survival", "island"], "popularity-page-2"],
  [950507, "Adventure Recall 07", ["odyssey", "quest"], "popularity-page-2"],
  [950508, "Adventure Recall 08", ["exploration", "artifact"], "rating-page-1"],
]);

export const D1_RECALL_FIXTURES = Object.freeze({
  movieExactCandidates: fixedMovieDescriptors.map(([id, title], index) => baseFixture({
    id,
    title,
    genreIds: [878, 18],
    keywords: ["space", "future"],
    source: "tmdb-seed-recommendations",
    popularity: 200 - index,
    extra: { reasonSeed: "Interstellar", seedTitle: "Interstellar" },
  })),
  tvExactCandidates: fixedTvDescriptors.map(([id, title], index) => baseFixture({
    id,
    title,
    mediaType: "tv",
    genreIds: [10765, 18],
    keywords: ["space", "future"],
    source: "tmdb-cross-media-discover:tv",
    popularity: 150 - index,
    extra: {
      reasonSeed: "Interstellar",
      seedTitle: "Interstellar",
      seedSupplement: true,
      crossMediaSeedGenreValues: ["genre-sf"],
    },
  })),
  animationExactCandidates: fixedAnimationDescriptors.map(([id, title, mediaType], index) => baseFixture({
    id,
    title,
    mediaType,
    contentType: "animation",
    genreIds: [16, mediaType === "tv" ? 10765 : 878],
    keywords: ["space", "robot"],
    source: `tmdb-cross-media-discover:${mediaType}`,
    popularity: 120 - index,
    extra: {
      displayContentType: "animation",
      reasonSeed: "Interstellar",
      seedTitle: "Interstellar",
      seedSupplement: true,
      crossMediaSeedGenreValues: ["genre-sf"],
    },
  })),
  adventureCandidates: fixedAdventureDescriptors.map(([id, title, keywords, source], index) => baseFixture({
    id,
    title,
    mediaType: "tv",
    genreIds: [10759],
    keywords,
    source,
    popularity: 180 - index,
  })),
  actionOnly: baseFixture({ id: 950401, title: "Action Evidence Only", mediaType: "tv", genreIds: [10759], keywords: ["combat", "chase"] }),
  adventureOnly: baseFixture({ id: 950402, title: "Adventure Evidence Only", mediaType: "tv", genreIds: [10759], keywords: ["journey", "expedition"] }),
  actionAdventureDual: baseFixture({ id: 950403, title: "Action Adventure Dual", mediaType: "tv", genreIds: [10759], keywords: ["combat", "journey"] }),
  sfOnly: baseFixture({ id: 950404, title: "SF Evidence Only", mediaType: "tv", genreIds: [10765], keywords: ["space", "robot"], country: "JP" }),
  fantasyOnly: baseFixture({ id: 950405, title: "Fantasy Evidence Only", mediaType: "tv", genreIds: [10765], keywords: ["magic", "dragon"], country: "JP" }),
  sfFantasyDual: baseFixture({ id: 950406, title: "SF Fantasy Dual", mediaType: "tv", genreIds: [10765], keywords: ["space", "magic"], country: "JP" }),
  warCandidates: Object.freeze([
    [950410, "War 01", ["army", "battle"]], [950411, "War 02", ["soldier", "combat"]],
    [950412, "War 03", ["military", "invasion"]], [950413, "War 04", ["war", "army"]],
    [950414, "War 05", ["battle", "soldier"]], [950415, "War 06", ["combat", "military"]],
    [950416, "War 07", ["invasion", "war"]], [950417, "War 08", ["army", "soldier"]],
  ].map(([id, title, keywords]) => baseFixture({ id, title, mediaType: "tv", genreIds: [10768], keywords, country: "GB" }))),
  politicsCandidates: Object.freeze([
    [950420, "Politics 01", ["government", "election"]], [950421, "Politics 02", ["parliament", "diplomacy"]],
    [950422, "Politics 03", ["president", "political"]], [950423, "Politics 04", ["government", "power"]],
    [950424, "Politics 05", ["election", "parliament"]], [950425, "Politics 06", ["diplomacy", "government"]],
    [950426, "Politics 07", ["coup", "president"]], [950427, "Politics 08", ["politics", "election"]],
  ].map(([id, title, keywords]) => baseFixture({ id, title, mediaType: "tv", genreIds: [10768], keywords, country: "GB" }))),
  horrorExact: baseFixture({ id: 950430, title: "Horror Exact", mediaType: "tv", genreIds: [9648], keywords: ["ghost", "haunting"], country: "US" }),
  horrorFalsePositive: baseFixture({ id: 950431, title: "Plain Mystery", mediaType: "tv", genreIds: [9648], keywords: ["investigation"], country: "US" }),
  highScoreDuplicate: baseFixture({ id: 950440, title: "Shared Localized Title", genreIds: [878], keywords: ["space"], popularity: 200, extra: { rating: 9, voteCount: 5000 } }),
  lowScoreDuplicate: baseFixture({ id: 950441, title: "Shared Localized Title", genreIds: [878], keywords: ["space"], popularity: 10, extra: { rating: 4, voteCount: 20 } }),
});