export const ANALYTICS_ELIGIBILITY = Object.freeze({
  ELIGIBLE: "ELIGIBLE",
  INELIGIBLE: "INELIGIBLE",
  SUPPRESS_UNRESOLVED: "SUPPRESS_UNRESOLVED",
  SUPPRESS_POLICY: "SUPPRESS_POLICY",
  SUPPRESS_JURISDICTION: "SUPPRESS_JURISDICTION",
  SUPPRESS_DENIED: "SUPPRESS_DENIED",
  SUPPRESS_WITHDRAWN: "SUPPRESS_WITHDRAWN",
  SUPPRESS_UNSUPPORTED: "SUPPRESS_UNSUPPORTED",
  SUPPRESS_NON_PRODUCTION: "SUPPRESS_NON_PRODUCTION",
});

export const ANALYTICS_RUNTIME_ENVIRONMENT = Object.freeze({
  UNRESOLVED: "UNRESOLVED",
  PRODUCTION: "PRODUCTION",
  PREVIEW: "PREVIEW",
  DEVELOPMENT: "DEVELOPMENT",
  QA: "QA",
  TEST: "TEST",
});

export const ANALYTICS_POLICY_STATE = Object.freeze({
  UNRESOLVED: "UNRESOLVED",
  ENABLED: "ANALYTICS_ENABLED",
  DISABLED: "ANALYTICS_DISABLED",
  UNSUPPORTED: "UNSUPPORTED_STATE",
});

export const LEGAL_JURISDICTION_STATE = Object.freeze({
  UNKNOWN: "JURISDICTION_UNKNOWN",
  REVIEW_REQUIRED: "LEGAL_REVIEW_REQUIRED",
  REQUIRES_EXPLICIT_OPT_IN: "ANALYTICS_REQUIRES_EXPLICIT_OPT_IN",
  ALLOWED: "ANALYTICS_ALLOWED_UNDER_APPROVED_POLICY",
  PROHIBITED_OR_UNSUPPORTED: "ANALYTICS_PROHIBITED_OR_UNSUPPORTED",
  UNSUPPORTED: "UNSUPPORTED_STATE",
});

export const ANALYTICS_CONSENT_STATE = Object.freeze({
  UNRESOLVED: "CONSENT_UNRESOLVED",
  NECESSARY_ONLY: "NECESSARY_ONLY",
  PREFERENCES_ALLOWED: "PREFERENCES_ALLOWED",
  ALLOWED: "ANALYTICS_ALLOWED",
  MARKETING_ALLOWED: "MARKETING_ALLOWED",
  DENIED: "ANALYTICS_DENIED",
  WITHDRAWN: "CONSENT_WITHDRAWN",
  UNSUPPORTED: "UNSUPPORTED_STATE",
});

export const ANALYTICS_MEASUREMENT_IDENTITY_STATE = Object.freeze({
  DISABLED: "MEASUREMENT_DISABLED",
  SESSION_ONLY: "SESSION_ONLY",
  UNSUPPORTED: "UNSUPPORTED_STATE",
});

export const ANALYTICS_ELIGIBILITY_INPUT = Object.freeze({
  runtimeEnvironment: ANALYTICS_RUNTIME_ENVIRONMENT.PRODUCTION,
  productPolicy: ANALYTICS_POLICY_STATE.ENABLED,
  jurisdictionState: LEGAL_JURISDICTION_STATE.ALLOWED,
  consentState: ANALYTICS_CONSENT_STATE.ALLOWED,
  measurementIdentityState: ANALYTICS_MEASUREMENT_IDENTITY_STATE.SESSION_ONLY,
});

export function resolveAnalyticsEligibility(input) {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNRESOLVED;
  }

  const runtimeValues = Object.values(ANALYTICS_RUNTIME_ENVIRONMENT);
  if (!runtimeValues.includes(input.runtimeEnvironment)) {
    return input.runtimeEnvironment == null
      ? ANALYTICS_ELIGIBILITY.SUPPRESS_UNRESOLVED
      : ANALYTICS_ELIGIBILITY.SUPPRESS_UNSUPPORTED;
  }
  if (input.runtimeEnvironment === ANALYTICS_RUNTIME_ENVIRONMENT.UNRESOLVED) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNRESOLVED;
  }
  if (input.runtimeEnvironment !== ANALYTICS_RUNTIME_ENVIRONMENT.PRODUCTION) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_NON_PRODUCTION;
  }

  if (input.productPolicy == null || input.productPolicy === ANALYTICS_POLICY_STATE.UNRESOLVED) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNRESOLVED;
  }
  if (input.productPolicy === ANALYTICS_POLICY_STATE.DISABLED) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_POLICY;
  }
  if (input.productPolicy !== ANALYTICS_POLICY_STATE.ENABLED) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNSUPPORTED;
  }

  if (input.jurisdictionState == null || input.jurisdictionState === LEGAL_JURISDICTION_STATE.UNKNOWN) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_JURISDICTION;
  }
  if (
    input.jurisdictionState === LEGAL_JURISDICTION_STATE.REVIEW_REQUIRED
    || input.jurisdictionState === LEGAL_JURISDICTION_STATE.REQUIRES_EXPLICIT_OPT_IN
    || input.jurisdictionState === LEGAL_JURISDICTION_STATE.PROHIBITED_OR_UNSUPPORTED
  ) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_JURISDICTION;
  }
  if (input.jurisdictionState !== LEGAL_JURISDICTION_STATE.ALLOWED) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNSUPPORTED;
  }

  if (
    input.consentState == null
    || input.consentState === ANALYTICS_CONSENT_STATE.UNRESOLVED
    || input.consentState === ANALYTICS_CONSENT_STATE.NECESSARY_ONLY
    || input.consentState === ANALYTICS_CONSENT_STATE.PREFERENCES_ALLOWED
    || input.consentState === ANALYTICS_CONSENT_STATE.MARKETING_ALLOWED
  ) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNRESOLVED;
  }
  if (input.consentState === ANALYTICS_CONSENT_STATE.DENIED) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_DENIED;
  }
  if (input.consentState === ANALYTICS_CONSENT_STATE.WITHDRAWN) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_WITHDRAWN;
  }
  if (input.consentState !== ANALYTICS_CONSENT_STATE.ALLOWED) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNSUPPORTED;
  }

  if (input.measurementIdentityState == null) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNRESOLVED;
  }
  if (input.measurementIdentityState !== ANALYTICS_MEASUREMENT_IDENTITY_STATE.SESSION_ONLY) {
    return ANALYTICS_ELIGIBILITY.SUPPRESS_UNSUPPORTED;
  }

  return ANALYTICS_ELIGIBILITY.ELIGIBLE;
}

export function isAnalyticsEligible(input) {
  return resolveAnalyticsEligibility(input) === ANALYTICS_ELIGIBILITY.ELIGIBLE;
}
